### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/pdf-rs-wasm#2]
- [x] better patch management
  - probably just hard-fork all deps within this repo (maybe git subtree?)
    - "squash" mode looks alright https://www.atlassian.com/git/tutorials/git-subtree
  - fixed by https://github.com/hi-ogawa/pdf-rs-wasm/pull/4
- [x] `impl Serialize for DrawItem`
  - fixed by https://github.com/hi-ogawa/pdf-rs-wasm/pull/7
- [ ] `impl Serialize for pdf::content::Op`
- [x] refactor monorepo
  - fixed by https://github.com/hi-ogawa/pdf-rs-wasm/pull/8
- [x] nodejs cli package
  - fixed by https://github.com/hi-ogawa/pdf-rs-wasm/pull/9
- [ ] web demo
- [ ] test with pdf2json test data https://github.com/modesty/pdf2json/tree/master/test

**Comment by hi-ogawa** [comment]
## table parsing example

```sh
pdf-rs-wasm-cli test/resources/pdf/table.pdf | jq '.pages[] | .items[] | select(.type == "Text") | { text: .data.text, y: .data.rect.y }' | jq -s 'group_by(.y)'
```

- input:  [table.pdf](https://github.com/hi-ogawa/pdf-rs-wasm/files/10367965/table.pdf)

<details><summary>output</summary>

```json
[
  [
    {
      "text": "Header 1.1",
      "y": 17.90094
    },
    {
      "text": "Header 1.2",
      "y": 17.90094
    },
    {
      "text": "Header 1.3",
      "y": 17.90094
    }
  ],
  [
    {
      "text": "Value 1.1",
      "y": 33.91986
    },
    {
      "text": "Value 1.2",
      "y": 33.91986
    },
    {
      "text": "Value 1.3",
      "y": 33.91986
    }
  ],
  [
    {
      "text": "Header 2.1",
      "y": 57.83821
    },
    {
      "text": "Header 2.2",
      "y": 57.83821
    },
    {
      "text": "Header 2.3",
      "y": 57.83821
    },
    {
      "text": "Header 2.4",
      "y": 57.83821
    }
  ],
  [
    {
      "text": "Value 1.1",
      "y": 73.85713
    },
    {
      "text": "Value 1.2",
      "y": 73.85713
    },
    {
      "text": "Value 1.3",
      "y": 73.85713
    },
    {
      "text": "Value 1.4",
      "y": 73.85713
    }
  ]
]
```

</details>

**Comment by hi-ogawa** [comment]
crash at `unwrap` https://github.com/pdf-rs/font/blob/393ec29a04a169d62208e5feb2aae4ecdd1324e0/src/opentype/base.rs#L60
